# Generated by Django 4.2.4 on 2023-09-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='Cronograma_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actividades.cronograma_actividad', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('asistio', 'Asistio'), ('no asistio', 'Inasistio')], max_length=20, verbose_name='Estado'),
        ),
    ]
