# Generated by Django 4.2.4 on 2023-08-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(verbose_name='Usuario')),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20, verbose_name='Estado')),
                ('fecha_asistencia', models.DateField(verbose_name='Fecha_asistencia')),
                ('horas', models.IntegerField(verbose_name='Horas')),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma_actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('id_labor_social', models.IntegerField(verbose_name='Actividad')),
                ('id_zona', models.IntegerField(verbose_name='Zona')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=5, verbose_name='Codigo del curso')),
                ('nombre_curso', models.CharField(max_length=5, verbose_name='Nombre del curso')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(verbose_name='Id del usuario')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de devolucion')),
                ('estado', models.CharField(choices=[('perdida', 'Perdida'), ('cerrado', 'Cerrado'), ('activo', 'Activo')], max_length=20, verbose_name='Estado')),
                ('id_inv_her', models.IntegerField(verbose_name='Id del inventario de la herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_est_her', models.IntegerField(verbose_name='id del estado de la herramieta')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('no disponible', 'Nodisponible')], max_length=15, verbose_name='Disponibilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Labor_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('id_wiki', models.IntegerField(verbose_name='Wiki')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion del rol')),
            ],
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('referencias_web', models.TextField(verbose_name='Referencias web')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la zona')),
            ],
        ),
    ]
