# Generated by Django 4.2.4 on 2023-08-30 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asistio', 'Bueno'), ('no asistio', 'Regular')], max_length=20, verbose_name='Estado')),
                ('fecha_asistencia', models.DateField(verbose_name='Fecha_asistencia')),
                ('horas', models.IntegerField(verbose_name='Horas')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'db_table': 'asistencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=5, verbose_name='Codigo del curso')),
                ('nombre_curso', models.CharField(max_length=5, verbose_name='Nombre del curso')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'db_table': 'curso',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estado_herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'estado_herramienta',
                'verbose_name_plural': 'estado_herramientas',
                'db_table': 'estado_herramienta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion del rol')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'rol',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('referencias_web', models.TextField(verbose_name='Referencias web')),
            ],
            options={
                'verbose_name': 'wiki',
                'verbose_name_plural': 'wikis',
                'db_table': 'wiki',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la zona')),
            ],
            options={
                'verbose_name': 'zona',
                'verbose_name_plural': 'zonas',
                'db_table': 'zona',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Labor_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('Wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wiki')),
            ],
            options={
                'verbose_name': 'labor_social',
                'verbose_name_plural': 'labores_sociales',
                'db_table': 'labor_social',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventario_herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('no disponible', 'Nodisponible')], max_length=15, verbose_name='Disponibilidad')),
                ('Estado_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado_herramienta')),
            ],
            options={
                'verbose_name': 'inventario_herramienta',
                'verbose_name_plural': 'inventario_herramientas',
                'db_table': 'inventario_herramienta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Historico_herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de devolucion')),
                ('estado', models.CharField(choices=[('perdida', 'Perdida'), ('cerrado', 'Cerrado'), ('activo', 'Activo')], max_length=20, verbose_name='Estado')),
                ('Inventario_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventario_herramienta')),
            ],
            options={
                'verbose_name': 'historico_herramienta',
                'verbose_name_plural': 'historico_herramientas',
                'db_table': 'historico_herramienta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cronograma_actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha_inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha_fin')),
                ('Labor_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.labor_social')),
                ('Zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zona')),
            ],
            options={
                'verbose_name': 'cronograma_actividad',
                'verbose_name_plural': 'cronograma_actividades',
                'db_table': 'cronograma_actividad',
                'ordering': ['id'],
            },
        ),
    ]
