# Generated by Django 4.2.4 on 2023-09-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asistio', 'Bueno'), ('no asistio', 'Regular')], max_length=20, verbose_name='Estado')),
                ('fecha_asistencia', models.DateField(verbose_name='Fecha_asistencia')),
                ('horas', models.IntegerField(verbose_name='Horas')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria_herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria herramienta',
                'verbose_name_plural': 'Categoria herramientas',
                'db_table': 'categoria_herramienta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=5, verbose_name='Codigo del curso')),
                ('nombre_curso', models.CharField(max_length=5, verbose_name='Nombre del curso')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'db_table': 'curso',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('no disponible', 'Nodisponible')], max_length=15, verbose_name='Disponibilidad')),
                ('Estado_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria_herramienta')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'db_table': 'herramienta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('referencias_web', models.TextField(verbose_name='Referencias web')),
            ],
            options={
                'verbose_name': 'Wiki',
                'verbose_name_plural': 'Wikis',
                'db_table': 'wiki',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la zona')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zona',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('Inventario_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.herramienta')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'db_table': 'prestamo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Labor_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('Wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wiki')),
            ],
            options={
                'verbose_name': 'Labor social',
                'verbose_name_plural': 'Labores sociales',
                'db_table': 'labor_social',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cronograma_actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha_inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha_fin')),
                ('Labor_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.labor_social')),
                ('Zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zona')),
            ],
            options={
                'verbose_name': 'Cronograma actividad',
                'verbose_name_plural': 'Cronograma actividades',
                'db_table': 'cronograma_actividad',
                'ordering': ['id'],
            },
        ),
    ]
