# Generated by Django 4.2.4 on 2023-09-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Inventario herramienta',
                'verbose_name_plural': 'Inventario herramientas',
                'db_table': 'inventario_herramienta',
                'ordering': ['id'],
            },
        ),
    ]
